name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run Endtest functional tests
        id: endtest_functional_tests
        uses: endtest-technologies/github-run-tests-action@v1.3.0.1.1
        with:
          app_id: "85205402"
          app_code: "79973826"
          api_request: "https://endtest.io/api.php?action=runTestSuite&appId=85205402&appCode=79973826&testSuite=106877&selectedPlatform=windows&selectedOs=a&selectedBrowser=chrome&selectedResolution=d&selectedLocation=sanfrancisco&selectedCases=491130&writtenAdditionalNotes="
          number_of_loops: 6
          
      - name: Get the test suite name output
        run: echo "${{ steps.endtest_functional_tests.outputs.test_suite_name }}"
        
      - name: Get the test suite name output1
        run: echo ${{ steps.endtest_functional_tests.outputs.test_suite_name }}
      
        
      - name: Get the configuration output
        run: echo "${{ steps.endtest_functional_tests.outputs.configuration }}"

      
      - name: Get multiple outputs
        run: |
          echo "${{ steps.endtest_functional_tests.outputs.test_suite_name }}"
          echo "${{ steps.endtest_functional_tests.outputs.configuration }}"
